In [1]:
import pandas as pd

In [2]:
places = pd.read_csv('../../dataset/places_v2.csv')
ratings = pd.read_csv('../../dataset/ratings.csv')
# df = df.dropna(axis=1, how="all")
# df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [3]:
places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Place_Id       441 non-null    int64
 1   Place_Name     441 non-null    object
 2   Description    441 non-null    object
 3   Category       441 non-null    object
 4   City           441 non-null    object
 5   Price          441 non-null    int64
 6   Rating         441 non-null    float64
 7   Time_Minutes   208 non-null    float64
 8   Coordinate     441 non-null    object
 9   Lat            441 non-null    float64
 10  Long           441 non-null    float64
 11  Unnamed: 11    0 non-null      float64
 12  Unnamed: 12    441 non-null    int64
 13  Working_Hours  159 non-null    object
dtypes: float64(5), int64(3), object(6)
memory usage: 48.4+ KB

In [8]:
places[places['Place_Id'] == 259]

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Coordinate,Lat,Long,Unnamed: 11,Unnamed: 12,Working_Hours
262,259,Monumen Perjuangan Rakyat Jawa Barat,Monumen Perjuangan Rakyat Jawa Barat (Monju) a...,Budaya,Bandung,0,4.5,45.0,"{'lat': -6.8934327, 'lng': 107.6185513}",-6.893433,107.618551,NaN,259,Kamis: 08.00–16.00 | Jumat: 08.00–16.00 | Sabt...

In [4]:
places['Place_Id'].nunique()

437

In [5]:
ratings['Place_Id'].nunique()

437

In [5]:
df[['Coordinate', 'Lat', 'Long']]

                                          Coordinate       Lat        Long
0            {'lat': -6.1753924, 'lng': 106.8271528} -6.175392  106.827153
1    {'lat': -6.137644799999999, 'lng': 106.8171245} -6.137645  106.817125
2    {'lat': -6.125312399999999, 'lng': 106.8335377} -6.125312  106.833538
3    {'lat': -6.302445899999999, 'lng': 106.8951559} -6.302446  106.895156
4               {'lat': -6.12419, 'lng': 106.839134} -6.124190  106.839134
..                                               ...       ...         ...
432          {'lat': -7.4338593, 'lng': 112.7199058} -7.433859  112.719906
433  {'lat': -7.291346799999999, 'lng': 112.7398218} -7.291347  112.739822
434          {'lat': -7.2752955, 'lng': 112.7549381} -7.275296  112.754938
435  {'lat': -7.294330299999999, 'lng': 112.7617534} -7.294330  112.761753
436          {'lat': -7.2420758, 'lng': 112.7368158} -7.242076  112.736816

[437 rows x 3 columns]

In [ ]:
# # Hitung jumlah Place_Name unik
# unique_place_names = df['Place_Name'].nunique()
# print(f"Jumlah Place_Name yang unik: {unique_place_names}\n")

# # Cetak semua kategori unik
# categories = df['Category'].unique()
# print(f"Kategori unik: {categories}\n")

# # Untuk setiap kategori, cetak jumlah data dan 10 data acak (hanya id dan Place_Name)
# for category in categories:
#     subset = df[df['Category'] == category]
#     print(f"Kategori: {category}")
#     print(f"Jumlah data: {len(subset)}")
#     print("10 data acak (id dan Place_Name):")
#     print(subset[['Place_Id', 'Place_Name']].sample(n=min(10, len(subset)), random_state=42))
#     print("="*80)

Jumlah Place_Name yang unik: 437

Kategori unik: ['Budaya' 'Taman Hiburan' 'Cagar Alam' 'Bahari' 'Pusat Perbelanjaan'
 'Tempat Ibadah']

Kategori: Budaya
Jumlah data: 117
10 data acak (id dan Place_Name):
     Place_Id                                         Place_Name
114       115                                   Monumen Sanapati
17         18                              Museum Bank Indonesia
146       147                    Bentara Budaya Yogyakarta (BBY)
106       107                                  Bangsal Pagelaran
38         39  Museum Macan (Modern and Contemporary Art in N...
337       338                                        Lawang Sewu
258       259               Monumen Perjuangan Rakyat Jawa Barat
374       375                                 Kota Lama Semarang
98         99                           Kampung Wisata Kadipaten
39         40                          Galeri Nasional Indonesia
================================================================================
Kategori: Taman Hiburan
Jumlah data: 135
10 data acak (id dan Place_Name):
     Place_Id                    Place_Name
320       321   Glamping Lakeside Rancabali
224       225          Orchid Forest Cikole
341       342                Taman Kasmaran
61         62      Taman Legenda Keong Emas
111       112      Bukit Bintang Yogyakarta
206       207                 Heha Sky View
42         43               The Escape Hunt
360       361  Wisata Kampung Krisan Clapar
404       405           Surabaya North Quay
424       425   Waterpark Kenjeran Surabaya
================================================================================
Kategori: Cagar Alam
Jumlah data: 106
10 data acak (id dan Place_Name):
     Place_Id                       Place_Name
390       391           Flower Farm Setiya Aji
141       142                      Ledok Sambi
92         93                 Gembira Loka Zoo
340       341  Hutan Wisata Tinjomoyo Semarang
387       388              Watu Gunung Ungaran
311       312   Taman Hutan Raya Ir. H. Juanda
217       218                      Kawah Putih
232       233                Gunung Papandayan
373       374                Hutan Pinus Kayon
142       143        Seribu Batu Songgo Langit
================================================================================
Kategori: Bahari
Jumlah data: 47
10 data acak (id dan Place_Name):
     Place_Id           Place_Name
187       188      Pantai Sadranan
201       202      Pantai Ngandong
186       187         Pantai Siung
343       344        Pantai Marina
184       185        Pantai Krakal
198       199       Pantai Sedahan
154       155      Pantai Ngobaran
176       177  Pantai Parangtritis
12         13        Pulau Pramuka
185       186        Pantai Glagah
================================================================================
Kategori: Pusat Perbelanjaan
Jumlah data: 15
10 data acak (id dan Place_Name):
     Place_Id                    Place_Name
83         84           Kawasan Kuliner BSM
159       160  Pasar Kebon Empring Bintaran
14         15                    Pasar Seni
283       284                    Pasar Baru
34         35          Grand Indonesia Mall
80         81             Mall Thamrin City
25         26                Pecinan Glodok
24         25             Pasar Tanah Abang
401       402   Food Junction Grand Pakuwon
33         34            Pasar Taman Puring
================================================================================
Kategori: Tempat Ibadah
Jumlah data: 17
10 data acak (id dan Place_Name):
     Place_Id                               Place_Name
21         22                          Masjid Istiqlal
22         23                          Gereja Katedral
277       278            Masjid Daarut Tauhiid Bandung
411       412                 Masjid Nasional Al-Akbar
351       352  GPIB Immanuel Semarang (Gereja Blenduk)
410       411                Masjid Muhammad Cheng Hoo
287       288                        Masjid Salman ITB
379       380                     Masjid Agung Ungaran
54         55                     Klenteng Jin De Yuan
301       302                            Masjid Pusdai
================================================================================

In [ ]:
# unique_places = df['Place_Name'].unique()

# # Mencetak setiap nama tempat yang unik
# for place in unique_places:
#     print(place)

Monumen Nasional
Kota Tua
Dunia Fantasi
Taman Mini Indonesia Indah (TMII)
Atlantis Water Adventure
Taman Impian Jaya Ancol
Kebun Binatang Ragunan
Ocean Ecopark
Pelabuhan Marina
Pulau Tidung
Pulau Bidadari
Pulau Pari
Pulau Pramuka
Pulau Pelangi
Pasar Seni
Jembatan Kota Intan
Museum Fatahillah
Museum Bank Indonesia
Kidzania
Museum Taman Prasasti
Museum Wayang
Masjid Istiqlal
Gereja Katedral
Museum Nasional
Pasar Tanah Abang
Pecinan Glodok
Sea World
Wisata Agro Edukatif Istana Susu Cibugary
Wisata Kuliner Pecenongan
Taman Menteng
Wisata Alam Mangrove Angke
Setu Babakan
Taman Suropati
Pasar Taman Puring
Grand Indonesia Mall
Skyrink - Mall Taman Anggrek
Bumi Perkemahan Cibubur
Istana Negara Republik Indonesia
Museum Macan (Modern and Contemporary Art in Nusantara)
Galeri Nasional Indonesia
Museum Bahari Jakarta
Museum Seni Rupa dan Kramik
The Escape Hunt
Monumen Selamat Datang
Jakarta Aquarium dan Safari
Pulau Semak Daun
Taman Situ Lembang
Taman Ismail Marzuki
Galeri Indonesia Kaya
Museum Joang 45
Jakarta Planetarium
Kampung Cina
Rumah Sipitung
Taman Agrowisata Cilangkap
Klenteng Jin De Yuan
Pantai Ancol
Taman Lapangan Banteng
Taman Ayodya
Museum Sumpah Pemuda
Museum Tekstil
Tugu Proklamasi
Taman Legenda Keong Emas
Museum Kebangkitan Nasional
Museum Sasmita Loka Ahmad Yani
Museum Basoeki Abdullah
Museum Layang-layang
Margasatwa Muara Angke
Pasar Petak Sembilan
Freedom Library
Perpustakaan Nasional
Cibubur Garden Diary (Cibugary)
Waterboom PIK (Pantai Indah Kapuk)
Museum Perangko
Museum Tengah Kebun
SnowBay Waterpark
Taman Cattleya
Taman Hutan Tebet
Hutan Kota Srengseng
Taman Spathodea
Plaza Indonesia
Mall Thamrin City
Museum Satria Mandala
Alive Museum Ancol
Kawasan Kuliner BSM
Taman Pintar Yogyakarta
Keraton Yogyakarta
Sindu Kusuma Edupark (SKE)
Museum Benteng Vredeburg Yogyakarta
De Mata Museum Jogja
Kampung Wisata Taman Sari
Situs Warungboto
Nol Kilometer Jl.Malioboro
Gembira Loka Zoo
Sumur Gumuling
Desa Wisata Sungai Code Jogja Kota
Alun Alun Selatan Yogyakarta
Monumen Yogya Kembali
Taman Pelangi Yogyakarta
Kampung Wisata Kadipaten
Taman Budaya Yogyakarta
Kampung Wisata Sosro Menduran
Monumen Batik Yogyakarta
Tugu Pal Putih Jogja
Tebing Breksi
Candi Donotirto
Kawasan Malioboro
Bangsal Pagelaran
Embung Tambakboyo
Hutan Pinus Pengger
Monumen Serangan Umum 1 Maret
Puncak Pinus Becici
Bukit Bintang Yogyakarta
Gedung Agung Yogyakarta
The Lost World Castle
Monumen Sanapati
Jurang Tembelan Kanigoro
The World Landmarks - Merapi Park Yogyakarta
Museum Sonobudoyo Unit I
Lava Bantal
Bukit Panguk Kediwung
Candi Prambanan
Watu Goyang
Kampung Wisata Rejowinangun
Kauman Pakualaman Yogyakarta
Alun-alun Utara Keraton Yogyakarta
Pantai Goa Cemara
Blue Lagoon Jogja
Gumuk Pasir Parangkusumo
Bukit Lintang Sewu
Studio Alam Gamplong
Watu Lumbung
Air Terjun Kedung Pedut
Puncak Kebun Buah Mangunan
Desa Wisata Gamplong
Kawasan Wisata Sosrowijayan
Grojogan Watu Purbo Bangunrejo
Wisata Alam Kalibiru
Jogja Exotarium
Puncak Gunung Api Purba - Nglanggeran
Bendung Lepen
Bunker Kaliadem Merapi
Ledok Sambi
Seribu Batu Songgo Langit
Goa Jomblang
Desa Wisata Rumah Domes/Teletubbies
Bukit Wisata Pulepayung
Bentara Budaya Yogyakarta (BBY)
Goa Rancang Kencono
Goa Cerme
Wisata Kraton Jogja
Desa Wisata Kelor
Pantai Patihan
Pantai Kukup
Pantai Ngrawe (Mesra)
Pantai Ngobaran
Pantai Pulang Sawal
Pantai Baron
Pantai Pok Tunggal
Hutan Pinus Asri
Pasar Kebon Empring Bintaran
Bukit Paralayang, Watugupit
Kampung Wisata Dipowinatan
Watu Mabur Mangunan
Pintoe Langit Dahromo
Green Village Gedangsari
Kebun Teh Nglinggo
Geoforest Watu Payung Turunan
Pantai Timang
Puncak Segoro
Candi Borobudur
Candi Ijo
Pantai Indrayanti
Pantai Nglambor
Pasar Beringharjo
Museum Ullen Sentalu
Museum Gunung Merapi
Pantai Parangtritis
Goa Pindul
Candi Ratu Boko
Pantai Depok Jogja
Pantai Sundak
Hutan Mangrove Kulon Progo
Jogja Bay Pirates Adventure Waterpark
Pantai Sepanjang
Pantai Krakal
Pantai Glagah
Pantai Siung
Pantai Sadranan
Pantai Nguluran
Pantai Samas
Pantai Drini
Air Terjun Sri Gethuk
Candi Sewu
Pantai Wediombo
Pantai Jogan
Pantai Ngrenehan
Pantai Jungwok
Pantai Greweng
Pantai Sedahan
Pantai Watu Kodok
Pantai Kesirat
Pantai Ngandong
Galaxy Waterpark Jogja
Desa Wisata Pulesari
Desa Wisata Tembi
Wisata Kaliurang
Heha Sky View
Taman Sungai Mudal
Pantai Sanglen
Pantai Congot
GunungTangkuban perahu
Jalan Braga
Gedung Sate
Trans Studio Bandung
Taman Hutan Raya Ir. H. Djuanda
Farm House Susu Lembang
Kebun Binatang Bandung
Kawah Putih
Tebing Karaton
Dusun Bambu
Museum Geologi Bandung
Museum Konferensi Asia Afrika
Masjid Raya Bandung
Dago Dreampark
Orchid Forest Cikole
Kawasan Punclut
Alun-Alun Kota Bandung
Museum Sri Baduga
Rabbit Town
Stone Garden Citatah
The Great Asia Africa
Bukit Moko
Gunung Papandayan
Amazing Art World
Gua Belanda
Taman Balai Kota Bandung
Panghegar Waterboom Bandung
Gunung Manglayang
Lembang Park & Zoo
Taman Lalu Lintas Ade Irma Suryani Nasution
Lawangwangi Creative Space
Curug Dago
Kampung Korea Bandung
Kampung Batu Malakasari
Jendela Alam
Curug Tilu Leuwi Opat
Kiara Artha Park
NuArt Sculpture Park
Upside Down World Bandung
Pesona Nirwana Waterpark & Cottages
Taman Lansia
Kampoeng Tulip
Selasar Sunaryo Art Space
Teras Cikapundung BBWS
Museum Barli
Wisata Batu Kuda
Monumen Bandung Lautan Api
Museum Gedung Sate
Monumen Perjuangan Rakyat Jawa Barat
Museum Pos Indonesia
Ciwangun Indah Camp Official
Wot Batu
Curug Batu Templek
Gereja Katedral Santo Petrus Bandung
Museum Mandala Wangsit Siliwangi
Caringin Tilu
Panama Park 825
Sudut Pandang Bandung
Bumi Perkemahan Batu Kuda
Bukit Bintang
Taman Vanda
Taman Budaya Jawa Barat
Curug Bugbrug
Babakan Siliwangi City Forest Path Bandung
Curug Cipanas
Taman Jomblo
Peta Park
Masjid Daarut Tauhiid Bandung
Masjid Agung Trans Studio Bandung
Gereja Tiberias Indonesia Bandung
Tektona Waterpark
Curug Cilengkrang
Jembatan Pasupati
Pasar Baru
Taman Sejarah Bandung
Roemah Seni Sarasvati
Puspa Iptek Sundial
Masjid Salman ITB
Curug Aseupan
Museum Pendidikan Nasional
Water Park Bandung Indah
Curug Anom
Taman Badak
Taman Film
Museum Nike Ardilla
Batununggal Indah Club
Mountain View Golf Club
Gunung Lalakon
Sendang Geulis Kahuripan
Sanghyang Heuleut
Lereng Anteng Panoramic Coffee Place
Masjid Pusdai
Masjid Al-Imtizaj
Situ Cileunca
Sunrise Point Cukul
Sungai Palayangan
Perkebunan Teh Malabar
Pemandian Air Panas Ciater
Observatorium Bosscha
Taman Bunga Cihideung
The Lodge Maribaya
Taman Hutan Raya Ir. H. Juanda
Taman Begonia
Tafso Barn
Curug Luhur Waterfall
Curug Malela
Curug Cimahi
Situ Patenggang
Kawah Rengganis Cibuni
Pemandian Air Panas Cimanggu
Glamping Lakeside Rancabali
Bukit Jamur
Kebun Tanaman Obat Sari Alam
Happyfarm Ciwidey
Saung Angklung Mang Udjo
Taman Kupu-Kupu Cihanjuang
Taman Miniatur Kereta Api
Gua Pawon
Bukit Gantole Cililin
Bandros City Tour
Kyotoku Floating Market
Rainbow Garden
Kota Mini
Chingu Cafe Little Seoul
Candi Gedong Songo
Grand Maerakaca
Kampung Pelangi
Lawang Sewu
Sam Poo Kong Temple
Desa Wisata Lembah Kalipancur
Hutan Wisata Tinjomoyo Semarang
Taman Kasmaran
Pantai Baruna
Pantai Marina
Kampoeng Djadhoel Semarang
Indonesia Kaya Park
Taman Pandanaran
Pura Giri Natha
Wisata Mangrove Tapak
Pantai Cipta
Old City 3D Trick Art Museum
GPIB Immanuel Semarang (Gereja Blenduk)
Taman Srigunting
Semarang Contemporary Art Gallery
Umbul Sidomukti
Saloka Theme Park
Wisata Alam Wana Wisata Penggaron
Masjid Kapal Semarang
Taman Bunga Celosia
Air Terjun Kali Pancur
Wisata Kampung Krisan Clapar
Danau Rawa Pening
Pantai Maron
Water Blaster Bukit Candi Golf
Waduk Jatibarang
Tirto Argo Siwarak
Wisata Lereng Kelir
Kampoeng Rawa
Monumen Palagan Ambarawa
Benteng Pendem
Wisata Eling Bening
Gua Maria Kerep Ambarawa
Museum Kereta Ambarawa
Hutan Pinus Kayon
Kota Lama Semarang
Semarang Chinatown
La Kana Chapel
Jembatan Biru Ambarawa
Goa Rong
Masjid Agung Ungaran
Tugu Muda Semarang
Kampoeng Kopi Banaran
Taman Tabanas
Kampung Tematik Jawi
Kampung Batik Gedong Semarang
Air Terjun Semirang
Obyek Wisata Goa Kreo
Watu Gunung Ungaran
Brown Canyon
Durian Gardens and Tourism Education Watu Simbar
Flower Farm Setiya Aji
Ekowisata Mangrove Wonorejo
Taman Harmoni Keputih
Air Mancur Menari
Taman Prestasi
Monumen Kapal Selam
Taman Kunang-Kunang
Taman Buah Surabaya
Taman Pelangi
Hutan Bambu Keputih
Taman Keputran
Food Junction Grand Pakuwon
Taman Barunawati
Kenjeran Park
Surabaya North Quay
Kebun Bibit Wonorejo
Taman Ekspresi Dan Perpustakaan
Kebun Binatang Surabaya
Rumah Batik
Ciputra Waterpark
Masjid Muhammad Cheng Hoo
Masjid Nasional Al-Akbar
Museum TNI AL Loka Jala Crana
Jembatan Merah
Museum De Javasche Bank
Keraton Surabaya
Klenteng Sanggar Agung
Museum Sepuluh Nopember Kota Surabaya
Monumen Tugu Pahlawan
Surabaya Museum (Gedung Siola)
Museum Kesehatan Dr. Adhyatma
Monumen Jalesveva Jayamahe
Patung Sura dan Buaya
Pantai Ria Kenjeran
Waterpark Kenjeran Surabaya
Balai Kota Surabaya
Patung Buddha Empat Rupa
Monumen Bambu Runcing Surabaya
House of Sampoerna
Atlantis Land Surabaya
Taman Hiburan Rakyat
Taman Mundu
Museum Mpu Tantular
Taman Bungkul
Taman Air Mancur Menari Kenjeran
Taman Flora Bratang Surabaya
Gereja Perawan Maria Tak Berdosa Surabaya

In [8]:
df.tail()

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Time_Minutes,Coordinate,Lat,Long
432,433,Museum Mpu Tantular,Museum Negeri Mpu Tantular adalah sebuah museu...,Budaya,Surabaya,2000,4.4,45.0,"{'lat': -7.4338593, 'lng': 112.7199058}",-7.433859,112.719906
433,434,Taman Bungkul,Taman Bungkul adalah taman wisata kota yang te...,Taman Hiburan,Surabaya,0,4.6,NaN,"{'lat': -7.291346799999999, 'lng': 112.7398218}",-7.291347,112.739822
434,435,Taman Air Mancur Menari Kenjeran,Air mancur menari atau dancing fountain juga a...,Taman Hiburan,Surabaya,0,4.4,45.0,"{'lat': -7.2752955, 'lng': 112.7549381}",-7.275296,112.754938
435,436,Taman Flora Bratang Surabaya,Taman Flora adalah salah satu taman kota di Su...,Taman Hiburan,Surabaya,0,4.6,NaN,"{'lat': -7.294330299999999, 'lng': 112.7617534}",-7.294330,112.761753
436,437,Gereja Perawan Maria Tak Berdosa Surabaya,Gereja Katolik Kelahiran Santa Perawan Maria m...,Tempat Ibadah,Surabaya,10000,4.8,NaN,"{'lat': -7.2420758, 'lng': 112.7368158}",-7.242076,112.736816

In [ ]:
# duplicates = df[df.duplicated(keep=False)]

# print("Duplicated rows:")
# print(duplicates)

Duplicated rows:
Empty DataFrame
Columns: [Place_Id, Place_Name, Description, Category, City, Price, Rating, Time_Minutes, Coordinate, Lat, Long]
Index: []